import type { Metadata } from "next";

import { Toaster } from "@/components/ui/toaster";
import { fontInstrumentSans } from "@/lib/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "devlinks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontInstrumentSans.variable} font-instrument-sans text-grey 3xl:container`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
